// <autogenerated />

using SerializationHelpers = DuckDbSharp.SerializationHelpers;

namespace DuckDbSharp.Example
{

    public static class AotSerializers
    {
        public static void RegisterAll()
        {
            SerializationHelpers.RegisterDeserializer(typeof(DuckDbSharp.Example.Employee), DeserializeColumns_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870, "94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870");
            SerializationHelpers.RegisterDeserializer(typeof(DuckDbSharp.Example.TeamsWithEmployees), DeserializeColumns_DuckDbSharp_Example_TeamsWithEmployees93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488, "93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488");
        }
        private static void DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_EmployeeId_0000000000000000000000000000000005000000000000000000000000000000(nint vectorPtr, DuckDbSharp.Example.Employee[] objects, int objectsLength)
        {
            var validityVector = SerializationHelpers.GetVectorValidity(vectorPtr);
            var vectorSpan = SerializationHelpers.GetVectorData<long>(vectorPtr, objectsLength);
            var i = 0;
            i = 0;
            while (true)
            {
                if (i >= vectorSpan.Length)
                {
                    break;
                }
            
                if (SerializationHelpers.IsPresent(validityVector, i))
                {
                    objects[i].EmployeeId = SerializationHelpers.ReadSpanItem(vectorSpan, i);
                }
                i++;
            }
        }

        private static void DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_FirstName_0000000000000000000000000000000011000000000000000000000000000000(nint vectorPtr, DuckDbSharp.Example.Employee[] objects, int objectsLength)
        {
            var validityVector = SerializationHelpers.GetVectorValidity(vectorPtr);
            var vectorSpan = SerializationHelpers.GetVectorData<DuckDbSharp.Types.DuckString>(vectorPtr, objectsLength);
            var i = 0;
            i = 0;
            while (true)
            {
                if (i >= vectorSpan.Length)
                {
                    break;
                }
            
                if (SerializationHelpers.IsPresent(validityVector, i))
                {
                    objects[i].FirstName = SerializationHelpers.DeserializeString(SerializationHelpers.ReadSpanItem(vectorSpan, i));
                }
                i++;
            }
        }

        private static void DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_LastName_0000000000000000000000000000000011000000000000000000000000000000(nint vectorPtr, DuckDbSharp.Example.Employee[] objects, int objectsLength)
        {
            var validityVector = SerializationHelpers.GetVectorValidity(vectorPtr);
            var vectorSpan = SerializationHelpers.GetVectorData<DuckDbSharp.Types.DuckString>(vectorPtr, objectsLength);
            var i = 0;
            i = 0;
            while (true)
            {
                if (i >= vectorSpan.Length)
                {
                    break;
                }
            
                if (SerializationHelpers.IsPresent(validityVector, i))
                {
                    objects[i].LastName = SerializationHelpers.DeserializeString(SerializationHelpers.ReadSpanItem(vectorSpan, i));
                }
                i++;
            }
        }

        private static System.Array DeserializeColumns_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870(nint chunk)
        {
            var rowCount = SerializationHelpers.GetChunkSize(chunk);
            var result = new DuckDbSharp.Example.Employee[rowCount];
            var i = 0;
            while (true)
            {
                if (i >= rowCount)
                {
                    break;
                }
            
                result[i] = new DuckDbSharp.Example.Employee();
                i++;
            }
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_EmployeeId_0000000000000000000000000000000005000000000000000000000000000000(SerializationHelpers.GetDataChunkVector(chunk, 0), result, rowCount);
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_FirstName_0000000000000000000000000000000011000000000000000000000000000000(SerializationHelpers.GetDataChunkVector(chunk, 1), result, rowCount);
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_LastName_0000000000000000000000000000000011000000000000000000000000000000(SerializationHelpers.GetDataChunkVector(chunk, 2), result, rowCount);
            
            return result;
        }

        private static void DeserializeField_DuckDbSharp_Example_TeamsWithEmployees93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488_TeamId_0000000000000000000000000000000004000000000000000000000000000000(nint vectorPtr, DuckDbSharp.Example.TeamsWithEmployees[] objects, int objectsLength)
        {
            var validityVector = SerializationHelpers.GetVectorValidity(vectorPtr);
            var vectorSpan = SerializationHelpers.GetVectorData<int>(vectorPtr, objectsLength);
            var i = 0;
            i = 0;
            while (true)
            {
                if (i >= vectorSpan.Length)
                {
                    break;
                }
            
                if (SerializationHelpers.IsPresent(validityVector, i))
                {
                    objects[i].TeamId = SerializationHelpers.ReadSpanItem(vectorSpan, i);
                }
                i++;
            }
        }

        private static void DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870(nint vectorPtr, DuckDbSharp.Example.Employee[] objects, int objectsLength)
        {
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_EmployeeId_0000000000000000000000000000000005000000000000000000000000000000(SerializationHelpers.GetStructureChildVector(vectorPtr, 0), objects, objectsLength);
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_FirstName_0000000000000000000000000000000011000000000000000000000000000000(SerializationHelpers.GetStructureChildVector(vectorPtr, 1), objects, objectsLength);
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870_LastName_0000000000000000000000000000000011000000000000000000000000000000(SerializationHelpers.GetStructureChildVector(vectorPtr, 2), objects, objectsLength);
        }

        private static void DeserializeField_DuckDbSharp_Example_TeamsWithEmployees93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488_Members_a7242c7e964cbcb6328de874bf0fab4ca7899d37caf4d0b8edf050935781d997(nint vectorPtr, DuckDbSharp.Example.TeamsWithEmployees[] objects, int objectsLength)
        {
            DuckDbSharp.Example.Employee[] sublist;
            int j, absIdx, sublistSize;
            var listValidityVector = SerializationHelpers.GetVectorValidity(vectorPtr);
            var elementValidityVector = SerializationHelpers.GetVectorValidity(SerializationHelpers.GetSublistChildVector(vectorPtr));
            var offsetsAndLengths = SerializationHelpers.GetVectorData<DuckDbSharp.Types.OffsetAndCount>(vectorPtr, objectsLength);
            var totalLength = SerializationHelpers.GetTotalItems(offsetsAndLengths, listValidityVector);
            var allSubItems = SerializationHelpers.RentArrayZeroed<DuckDbSharp.Example.Employee>(totalLength);
            var rowId = 0;
            while (true)
            {
                if (rowId >= totalLength)
                {
                    break;
                }
            
                if (SerializationHelpers.IsPresent(elementValidityVector, rowId))
                {
                    allSubItems[rowId] = new DuckDbSharp.Example.Employee();
                }
            
                rowId++;
            }
            DeserializeField_DuckDbSharp_Example_Employee94ff1bff6aa28b7ba407b6e2361836e178ecb0f682ff5bece61371e8ec489870(SerializationHelpers.GetSublistChildVector(vectorPtr), allSubItems, totalLength);
            rowId = 0;
            while (true)
            {
                if (rowId >= objectsLength)
                {
                    break;
                }
            
                if (SerializationHelpers.IsPresent(listValidityVector, rowId))
                {
                    sublistSize = SerializationHelpers.GetSublistSize(offsetsAndLengths, rowId);
                    sublist = SerializationHelpers.CreateArray<DuckDbSharp.Example.Employee>(sublistSize);
                    absIdx = SerializationHelpers.GetSublistOffset(offsetsAndLengths, rowId);
                    j = 0;
                    while (true)
                    {
                        if (j >= sublistSize)
                        {
                            break;
                        }
            
                        sublist[j] = allSubItems[absIdx];
                        absIdx++;
                        j++;
                    }
                    objects[rowId].Members = sublist;
                }
                rowId++;
            }
            SerializationHelpers.ReleaseArray<DuckDbSharp.Example.Employee>(allSubItems);
        }

        private static System.Array DeserializeColumns_DuckDbSharp_Example_TeamsWithEmployees93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488(nint chunk)
        {
            var rowCount = SerializationHelpers.GetChunkSize(chunk);
            var result = new DuckDbSharp.Example.TeamsWithEmployees[rowCount];
            var i = 0;
            while (true)
            {
                if (i >= rowCount)
                {
                    break;
                }
            
                result[i] = new DuckDbSharp.Example.TeamsWithEmployees();
                i++;
            }
            DeserializeField_DuckDbSharp_Example_TeamsWithEmployees93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488_TeamId_0000000000000000000000000000000004000000000000000000000000000000(SerializationHelpers.GetDataChunkVector(chunk, 0), result, rowCount);
            DeserializeField_DuckDbSharp_Example_TeamsWithEmployees93a3e2d7c2915a92eeb006194c788ece8ebc0c75c62a027fc8577bcd3c8f6488_Members_a7242c7e964cbcb6328de874bf0fab4ca7899d37caf4d0b8edf050935781d997(SerializationHelpers.GetDataChunkVector(chunk, 1), result, rowCount);
            
            return result;
        }

    }
}
