// <autogenerated />

#nullable enable
#pragma warning disable CS8618

using DuckDbIncludeAttribute = DuckDbSharp.DuckDbIncludeAttribute;
using DuckDbGeneratedTypeAttribute = DuckDbSharp.DuckDbGeneratedTypeAttribute;
using TypedDuckDbConnectionBase = DuckDbSharp.TypedDuckDbConnectionBase;

namespace DuckDbSharp.Example
{
    public static class Queries
    {
        /// <summary>
        /// <code>
        /// select
        ///     ? as EmployeeId,
        ///     'first' as FirstName,
        ///     'last' as LastName,
        /// </code>
        /// </summary>
        public static System.Collections.Generic.IEnumerable<DuckDbSharp.Example.Employee> ExecuteQuery_GetEmployeeById(this TypedDuckDbConnectionBase db, long p1)
        {
            return db.Execute<DuckDbSharp.Example.Employee>(
@"select 
    ? as EmployeeId,
    'first' as FirstName,
    'last' as LastName,", new object[] { p1 });
        }

        /// <summary>
        /// <code>
        /// select
        ///     1 as TeamId,
        ///     [
        ///         { EmployeeId: 6::long, FirstName: 'Susan', LastName: 'Smith' },
        ///         { EmployeeId: 7::long, FirstName: 'John', LastName: 'Doe' },
        ///     ] as Members
        /// union
        /// select
        ///     2 as TeamId,
        ///     [] as Members
        /// </code>
        /// </summary>
        public static System.Collections.Generic.IEnumerable<DuckDbSharp.Example.TeamsWithEmployees> ExecuteQuery_teams_with_employees(this TypedDuckDbConnectionBase db)
        {
            return db.Execute<DuckDbSharp.Example.TeamsWithEmployees>(
@"select
    1 as TeamId,
    [
        { EmployeeId: 6::long, FirstName: 'Susan', LastName: 'Smith' },
        { EmployeeId: 7::long, FirstName: 'John', LastName: 'Doe' },
    ] as Members
union
select
    2 as TeamId,
    [] as Members");
        }

    }
    [DuckDbGeneratedType]
    public class TeamsWithEmployees
    {
        [DuckDbInclude]
        public int TeamId;
        [DuckDbInclude]
        public DuckDbSharp.Example.Employee[] Members;
    }
}
