// <autogenerated />

#nullable enable
#pragma warning disable CS8618

using DuckDbIncludeAttribute = DuckDbSharp.DuckDbIncludeAttribute;
using DuckDbGeneratedTypeAttribute = DuckDbSharp.DuckDbGeneratedTypeAttribute;
using TypedDuckDbConnectionBase = DuckDbSharp.TypedDuckDbConnectionBase;

namespace DuckDbFuzzingGeneratedTypes
{
    public static class Queries
    {
        /// <summary>
        /// <code>
        /// select * from myfunc()
        /// </code>
        /// </summary>
        public static System.Collections.Generic.IEnumerable<DuckDbSharp.FuzzingTypes.MyClass> ExecuteQuery_MyClassQuery(this TypedDuckDbConnectionBase db)
        {
            return db.Execute<DuckDbSharp.FuzzingTypes.MyClass>(
"select * from myfunc()");
        }

    }
}
